#ifndef __TAGCRYPTVERSION_H__
#define __TAGCRYPTVERSION_H__

#define TAGCRYPT_PACKET_MAGIC_NUM   0x02F595A8
#define TAGCRYPT_PKEY_MAGIC_NUM     0x02F595A9
#define TAGCRYPT_SKEY_MAGIC_NUM     0x02F595B0

#define TAGCRYPT_SIGNATURE_MAJOR    2ul
#define TAGCRYPT_SIGNATURE_MINOR    1ul

#define TAGCRYPT_PKEY_MAJOR         1ul
#define TAGCRYPT_PKEY_MINOR         1ul

#endif /*__TAGCRYPTVERSION_H__*/
